name: Build Help

on:
  push:

jobs:

  help:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Help
        run: |
          ./configure --help
